---
- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        # `../vars/` is required because `with_first_found` looks in the
        # `files/` directory.  See Ansible issues [7788][], [5108][] and this
        # [page][] for details:
        #
        # [7788]: https://github.com/ansible/ansible/issues/7788
        # [5108]: https://github.com/ansible/ansible/issues/5108
        # [page]: https://groups.google.com/forum/#!topic/ansible-project/UQ_ArPEofFU
        - ../vars/installer


- include: 'installer/apt.yml'
  when: 'lsbrelease_installer == "apt"'

- include: 'installer/pacman.yml'
  when: 'lsbrelease_installer == "pacman"'

- include: 'installer/zypper.yml'
  when: 'lsbrelease_installer == "zypper"'

- include: 'installer/dnf.yml'
  when: 'lsbrelease_installer == "dnf"'

- include: 'installer/yum.yml'
  when: 'lsbrelease_installer == "yum"'

- include: 'installer/portage.yml'
  when: 'lsbrelease_installer == "portage"'

- include: 'installer/default.yml'
  when: 'lsbrelease_installer == "default"'
